BUTTON1_FIND = "Найти вишлист 🔎"
BUTTON2_MAKE = "Создать вишлист 📝"
BUTTON3_SHOW = "Показать все мои вишлисты ⚙️"
BUTTON4_GENERATE_POSTCARD = "Я совершил пожертвование!"
BUTTON5_ANONYMOUS_SEND = "Отправить анонимно"
BUTTON6_ADD_NAME = "Подписать открытку"
BUTTON7_ADD_SCREENSHOT = "Добавить скриншот перевода"
BUTTON8_NO_SCREENSHOT = "Отправить без скриншота"
BUTTON9_READY = "Отправить!"
BUTTON10_DELETE_WISHLIST = "Удалить вишлист"

CALLBACK_BUTTON1_FIND = "callback_button_find"
CALLBACK_BUTTON2_MAKE = "callback_button_make"
CALLBACK_BUTTON3_SHOW = "callback_button_show"
CALLBACK_BUTTON4_GENERATE_POSTCARD = "callback_button_generate_postcard"
CALLBACK_BUTTON5_ANONYMOUS_SEND = "callback_button_anonymous_send"
CALLBACK_BUTTON6_ADD_NAME = "callback_button_add_name"
CALLBACK_BUTTON7_ADD_SCREENSHOT = "callback_button_add_screenshot"
CALLBACK_BUTTON8_NO_SCREENSHOT = "callback_button_no_screenshot"
CALLBACK_BUTTON9_READY = "callback_button_ready"
CALLBACK_BUTTON10_DELETE_WISHLIST = "callback_button_delete_wishlist"

BUTTON_PIC0 = "1"
BUTTON_PIC1 = "2"
BUTTON_PIC2 = "3"
BUTTON_PIC3 = "4"

CALLBACK_BUTTON_PIC0 = "callback_button_pic1"
CALLBACK_BUTTON_PIC1 = "callback_button_pic2"
CALLBACK_BUTTON_PIC2 = "callback_button_pic3"
CALLBACK_BUTTON_PIC3 = "callback_button_pic4"

CALLBACK_BUTTON_8MARCH_PIC1 = "callback_button_8march_pic1"
CALLBACK_BUTTON_8MARCH_PIC2 = "callback_button_8march_pic2"